---
- name: list running instances
  ec2_instance_info:
    filters:
      "tag:Name": "{{ aws_ec2_name }}"
  register: _instances

- name: delete virtual machine
  amazon.aws.ec2_instance:
    instance_ids: "{{ _instances.instances | map(attribute='instance_id') | list }}"
    wait: true
    state: absent

- name: delete key pair
  amazon.aws.ec2_key:
    name: "{{ aws_key_pair }}"
    state: absent

- name: get VPC info
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ aws_vpc_name }}"
  register: _vpc

- block:
    - name: delete internet gateway attached to the VPC
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ _vpc.vpcs.0.id }}"
        state: absent
      register: internet_gw

    - name: delete security group
      amazon.aws.ec2_security_group:
        name: "{{ aws_security_group }}"
        vpc_id: "{{ _vpc.vpcs.0.id }}"
        state: absent
      register: rds_security_group

    - name: delete Subnets
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ _vpc.vpcs.0.id }}"
        cidr: "{{ aws_subnet_cidr }}"
        state: absent

    - name: delete Route table for internet gateway
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ _vpc.vpcs.0.id }}"
        lookup: tag
        resource_tags: "{{ aws_internet_gw_tags }}"
        state: absent

    - name: delete a VPC
      amazon.aws.ec2_vpc_net:
        cidr_block: "{{ aws_vpc_cidr }}"
        name: "{{ aws_vpc_name }}"
        state: absent

  when: _vpc.vpcs | length > 0