---
- name: Delete resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"
    force_delete_nonempty: true
    state: absent
